logo:
  enable: false
  lightmode: null
  darkmode: null
favicon: false
timeformat: "MMM, D YYYY"
podcast: true
lazyload: true
copyright: 'All rights reserved.'
highlight:
  enable: true
  lightmode: 'atom-one-light'
  darkmode: 'atom-one-dark'
navbar:
  - ['mailto:privet@utc3.live', 'fa fa-paper-plane', '']
  - ['https://github.com/guiqiqi/chromate', 'fa fa-github', '']
  - ['/feed.rss', 'fa fa-rss', '']
menubar:
  - ['/about/', 'About']
  - ['/archives/', 'Archives']
rss:
  enable: true
  path: '/feed.rss'
  config:
    email: 'privet@utc3.live'
    category: 'Education'
    explicit: false